# Generated by Django 2.2.7 on 2019-11-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modoficación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('EmEmp_Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'EmEmp_Empresa',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modoficación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('GmGru_Name', models.CharField(max_length=80, unique=True, verbose_name='Nombre de Grupo')),
                ('GmGru_Permissions', models.ManyToManyField(to='auth.Permission')),
            ],
            options={
                'db_table': 'GmGru_Grupo',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modoficación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('ImItm_Nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Item')),
                ('ImItm_Url', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Url de Item')),
                ('ImItm_Icono', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Icono de FontAwesome')),
                ('ImItm_GrupoPermisos', models.ManyToManyField(to='menu.Grupo')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'ImItm_Item',
            },
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modoficación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('SId_Nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Modelo Enlazado')),
                ('SId_Url', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Url de SubItem')),
                ('SId_ItemPadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Item')),
                ('SId_Modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Sub Item',
                'verbose_name_plural': 'Subs Items',
                'db_table': 'SId_SubItem',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modoficación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('MmMen_Empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Empresa')),
                ('MmMen_Item', models.ManyToManyField(to='menu.Item')),
                ('MmMen_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MmMen_Menu',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSeleccionada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modoficación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('ESd_Nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('ESd_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ESd_EmpresaSeleccionada',
            },
        ),
    ]
