# Generated by Django 2.2.7 on 2019-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UmUsr_Username', models.CharField(max_length=255, unique=True)),
                ('UmUsr_Email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('UmUsr_Nombres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('UmUsr_Apellidos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('UmUsr_UsuarioActivo', models.BooleanField(default=True)),
                ('UmUsr_UsuarioAdministrador', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UmUsr_Usuario',
            },
        ),
    ]
